server:
  port: 9002


spring:
  application:
    admin: query-event-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST_IP:localhost}:5432/eventservice
    username: ${POSTGRESQL_USERNAME:eventservice}
    password: ${POSTGRESQL_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

axon:
  snapshot:
    trigger:
      treshold:
        event: 100
  distributed:
    enabled: true
  serializer:
    messages: jackson